### ISSUE TITLE
More fonts in one AttributedTextView

### ISSUE THREAD

**Issue by vojtaBelovsky** [evermeer/AttributedTextView#15]
Hello,

I need to have more fonts in one AttributedTextView instance. For example:

User1 followed ("myFontRegular") User2("myFontBold")

I tried it to implement in many ways, but I found out that only first font is applied to whole text in AttributedTextView. Here is sample of my implementation:

            statusLabel.attributer =
                name.color(.charcoal).font(.graphik(15))
                .append(" followed ").color(.aluminium).font(.graphik(15))
                .append("\(post.follow_display_name ?? "some user")").makeInteract({ _ in
                    if let followId = post.follow_user_id {
                        self.callback?(.user, followId)
                    }
                })
                .setLinkColor(.darkGreen).font(.graphikBold(15))

But result of this implementation is that whole text is in graphik font, not graphik and graphikBold. I tried to change sizes, and these are applied correctly, but different fons not. Is it somehow possible to achieve what I need by using AttributedTextView?

Thanks,

Vojta

**Comment by evermeer** [comment]
I'm not sure what's going on here. You do have to be aware that a label (statusLabel?) can not use makeInteract. You need a textview for that. 

The setLinkColor will set the link color property on the textView. You can only set it for the entire textview. You cannot have diverent colors.

I assume your .graphik .charcoal .aluminium an .graphikBold are valid UIColor and UIFont implementations.

I just did a test with some of the default fonts an this works:
```
textView1.attributer = "Edwin".red.fontName("Baskerville").size(15)
    .append("Edwin").gray.font(UIFont(name: "SourceSansPro-Regular", size: 15))
    .append("Edwin").makeInteract({ _ in
    }).fontName("Helvetica").size(18)
    .setLinkColor(.orange)
attributedText = textView1.attributedText // View the details for this -->

```

**Comment by evermeer** [comment]
If you still have a problem with this, then just let me know.
