### ISSUE TITLE
AttributedTextView's append(_:) method in String+Attributer.swift conflicts with Swift's append(_:)

### ISSUE THREAD

**Issue by vitalii-tym** [evermeer/AttributedTextView#18]
Including AttributedTextView in a project, which has at least one piece of code using 'append(_:) results in _Ambiguous use of 'append'_ compiler error:

<img width="1234" alt="screenshot 2018-04-17 18 36 27" src="https://user-images.githubusercontent.com/5410835/38880633-dbe70fb0-426e-11e8-8f96-72295ebefeb0.png">

**Comment by evermeer** [comment]
Thanks for your PR. It's now published as version 0.9.0.
