### ISSUE TITLE
Can this work in iOS 9?

### ISSUE THREAD

**Issue by kennebecstars** [evermeer/AttributedTextView#21]
I know makeInteract uses 10.0 features. Is there a way to use this for iOS 9?

**Comment by evermeer** [comment]
It should already be working for iOS9. It should even work with iOS8.
If you take a look at the AttributedTextView.swift file, then at the bottom you see the 2 interact functions having both a variant for iOS 10+ and a variant for 7 to 10.

I just downloaded the iOS9 simulator and executed the demo app on it and ... indeed the demo itself uses an iOS 10 specific feature for opening an URL. I just updated the demo and it can now run on iOS 9

But... For some reason the .makeInteract does not work after navigating to the second sample... I will have a look at that now.

**Comment by kennebecstars** [comment]
The tough thing about the two varients is: they just do nothing if you are not using the delegate correctly.

**Comment by evermeer** [comment]
I used a delegate chaining method so that I could handle the events in the control itself. Apparently there is an issue with setting the super.delegate more than once. I am now setting the delegate only once in the init and that seems to work. I just published version 0.9.1 with an update for this.

**Comment by kennebecstars** [comment]
Maybe setting the delegate a second time resets tracking its behaviors? I will check the fixes. Merci!

**Comment by kennebecstars** [comment]
Worked great! Did this project decouple from the cocoapod? Its versions seem off-track. But, it seems there is no merge conflict. Can it be pushed?!

**Comment by evermeer** [comment]
What do you mean?
Looking at Cocoapods I see that the latest published version is 0.9.1 https://cocoapods.org/pods/AttributedTextView
Which is indeed this version with the delegate fix for iOS 9
The Demo application is build against the AttributedTextView-iOS framework which is just part of the solution and therefore will always use the latest version.
There are no open changes. Everything is pushed.
