### ISSUE TITLE
Disable selection for textView

### ISSUE THREAD

**Issue by 10000TB** [evermeer/AttributedTextView#26]
Is it possible you can help not enabling selection on textView when setting attributer ? In some scenario, text selection is really annoying and undesirable as we just want users be able to click and press (with textSelection enabled, it often pop up with some selected text when user long press)

**Comment by evermeer** [comment]
Only when you have used .makeInteract it will set these properties:
                self.isUserInteractionEnabled = true
                self.isSelectable = true
                self.isEditable = false
Without these the .makeInteract will not work.
If you do not want this behavior, then don't use makeInteract.
This is standard UITextView behavior.

**Comment by 10000TB** [comment]
Thanks @evermeer !  
sadly, I am using the `.makeInteract` to make username clickable in a textview:
  
*user1* : this is great 
  
but really need to make the whole textview not clickable, would it work if I put a overlay view on top of the textview ? 

Any workaround/hack suggestion ?

**Comment by 10000TB** [comment]
that makes sense

no worries, thank you very much for the reply!
