### ISSUE TITLE
Error when compiling in xcode 10 swift 4.2

### ISSUE THREAD

**Issue by ljbdelacruz** [evermeer/AttributedTextView#27]
i received this error when using this dependency on branch XCode10 does anyone have a idea how to solve this? would really appreciate it thanks
"The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions""

<img width="817" alt="screen shot 2018-12-06 at 9 22 09 am" src="https://user-images.githubusercontent.com/22063776/49554799-7b7bdd00-f938-11e8-86e3-e0f5f77c5c0c.png">

**Comment by evermeer** [comment]
An error like this usually comes up fast when using the + to append various texts. The compiler then needs to examine every possible type where the + can apply to. In this case you are using .append which should have been fine. Is this the complete line of code? Or is there more?

One thing what you could do is splitting the statement up in separate variables and then append those to the contactInfoLabel.attributer. You would then get something like
```
var header = empty.append(...
var email = "Email: ".localized.append(info....
var address = "Address: ".localized.append(info....
contactInfoLabel = header.append(email).append(address)
```

**Comment by evermeer** [comment]
I assume you were able to solve your issue? If not, then just let me know.
