### ISSUE TITLE
UITextViewDelegate should return values based on isEditable

### ISSUE THREAD

**Issue by maksg** [evermeer/AttributedTextView#31]
If the following UITextViewDelegate methods are not implemented they always return false. I think it would be much better if the return value was based on the TextView's isEditable property.

`textViewShouldBeginEditing(_ textView: UITextView)`
`textViewShouldEndEditing(_ textView: UITextView)`
`textView(_ textView: UITextView, shouldChangeTextIn range: NSRange, replacementText text: String)`

**Comment by evermeer** [comment]
Do you mean these AttributedTextView implementation?

```
    public func textViewShouldBeginEditing(_ textView: UITextView) -> Bool {
        return _delegate?.textViewShouldBeginEditing?(textView) ?? false
    }    
    public func textViewShouldEndEditing(_ textView: UITextView) -> Bool {
        return _delegate?.textViewShouldEndEditing?(textView) ?? false
    }
    public func textView(_ textView: UITextView, shouldChangeTextIn range: NSRange, replacementText text: String) -> Bool {
        return _delegate?.textView?(textView, shouldChangeTextIn: range, replacementText: text) ?? false
    }
```

Ah, I see, true is even the default
https://developer.apple.com/documentation/uikit/uitextviewdelegate/1618608-textviewshouldbeginediting

I will change it.

**Comment by evermeer** [comment]
This has now been pushed as version 1.3.0
The code has also been tested with Swift 5
