### ISSUE TITLE
How can I change truncation text when textview clip?

### ISSUE THREAD

**Issue by veila** [evermeer/AttributedTextView#32]

**Comment by evermeer** [comment]
It's standard UITextview behavior. What do you want? You could enable scroll or let the text be truncated. 
Here are some sample tips of what you could do:
https://stackoverflow.com/questions/18696706/large-text-being-cut-off-in-uitextview-that-is-inside-uiscrollview

**Comment by veila** [comment]
I want if my text over 18 lines, textview set tail truncation as "See more", click that I can set max lines = 0 and expand it

**Comment by evermeer** [comment]
Ah, you want non default behavior. I think you could use this project:
https://github.com/ilyapuchka/ReadMoreTextView
probably together with AttributedTextView
