### ISSUE TITLE
Update padding between underline and text 

### ISSUE THREAD

**Issue by Ammannaidu1** [evermeer/AttributedTextView#34]
Default behaviour is under line trimmed in case of g. I want to add custom padding to underline and text

<img width="291" alt="Screenshot 2020-06-19 at 10 45 02 AM" src="https://user-images.githubusercontent.com/49372537/85099042-fc987d80-b219-11ea-9bac-ecfdc7c58719.png">

**Comment by evermeer** [comment]
unfortunately NSAttributedString does not support that sort of underline customisations. See
https://stackoverflow.com/questions/27710514/nsunderlinestyleattributename-underline-spacing
and https://stackoverflow.com/questions/43785665/underline-covers-text-in-nsattributedstring?rq=1
