### ISSUE TITLE
Using Swift Package Manager

### ISSUE THREAD

**Issue by vinamelody** [evermeer/AttributedTextView#36]
Hi, I am trying to add via SPM but getting this error. Could you help?

![Screenshot 2021-01-10 at 10 17 42 AM](https://user-images.githubusercontent.com/990511/104112691-1e2f9280-532d-11eb-8367-317b772cca49.png)

Thank you in advanced!

**Comment by evermeer** [comment]
Sorry, I don't think I can help you. SPM support is only here because it was in the initial setup template of the project. I have no experience with SPM. I always use Cocoapods. Maybe someone else can help?

**Comment by vinamelody** [comment]
Hi @evermeer Ii want to try importing as `Add the downloaded AttributedTextView.framework.` but not sure how. I choose iOS and build, get the .framework inside Product folder. 
But when I add in my project, I see this error 
![Screenshot 2021-01-10 at 7 52 55 PM](https://user-images.githubusercontent.com/990511/104122027-8efe9b00-537d-11eb-9da4-06d94f082eae.png)

**Comment by Svantulden** [comment]
PR is open to add support: https://github.com/evermeer/AttributedTextView/pull/39
